config/routes.rb
Rails.application.routes.draw do

  devise_for :admins, :controllers => {
    sessions: 'admins/sessions',
    passwords: 'admins/passwords',
    registrations: 'admins/registrations'
   }
  namespace :admin do
    resources :users, only: [:index, :show, :edit, :update, :destroy]
    resources :products, only: [:new, :create, :index, :show, :edit, :update, :delete]
    resources :genres, only: [:index, :create, :update, :destroy, :edit] do
      member do
        patch 'genre_restore'
      end
    end
    resources :orders, only: [:index, :show, :update]
    get 'top' => 'admins#top'
  end


  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations'
  }
  root 'products#index'
  get '/products/:genre_id/genre', to:'products#index', as: 'genres'
  resources :users, only: [:show]
  resources :products, only: [:index, :show]
  resources :carts, only: [:create, :index, :destroy, :update]
  delete '/carts_delete' => 'carts#carts_delete' ,as: 'carts_delete'

  resources :orders, only: [:new, :create, :index, :show] do
    collection do
      post 'check'
      get 'finish'
    end
  end
  get '/orders_check' => 'orders#check',as: 'orders_check'
  resources :sends, only: [:edit, :index, :delete, :update, :create]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord
	belongs_to :user
	has_many :order_products
	accepts_nested_attributes_for :order_products
	enum payment_method: {クレジットカード: 1, 銀行振込: 2}
	enum order_status: {入金待ち: 1, 入金済み: 2, 発送済み: 3}
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
    before_action :authenticate_admin!
# 注文履歴表示
    def index
        @orders = Order.page(params[:page]).reverse_order
    end
# 注文詳細表示
    def show
    	@order = Order.find(params[:id])
        @user = @order.user
        @order_products = @order.order_products
    end
#注文ステータス、販売ステータスの変更（詳細ページ)
    def update
        @order = Order.find(params[:id])
        @order.update(order_params)
        redirect_to admin_orders_path
    end
private
    def order_params
        params.require(:order).permit(:user_id, :name, :postcode, :address, :delivery_cost, :total_price, :order_status, :payment_method, order_products_attributes:[:id, :make_status])
    end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!
# 注文情報入力ページorder_productモデル
    def new
        @order = Order.new
        @sends = Send.all
    end
# 注文確認ページ
    def check
        @order = Order.new(order_params)
        @carts = current_user.carts
        if params[:add] == "my_addr"
            @order.postcode = current_user.postcode
            @order.address = current_user.address
            @order.name = current_user.last_name + current_user.first_name
        elsif params[:add] == "send_addr"
            @send = Send.find(params[:send][:send_id])
            @order.postcode = @send.postcode
            @order.address = @send.address
            @order.name = @send.name
        elsif params[:add] == "new_addr"
            @send = Send.new(user_id: current_user.id)
            @send.postcode = @order.postcode
            @send.address = @order.address
            @send.name = @order.name
            @send.save
            render :check
        else
            render :new
        end
    end
# 注文完了ページ
    def finish
    end
# 注文情報を保存
    def create
        @order = Order.new(order_params)
        @order.user_id = current_user.id
        @order.save
        @carts = current_user.carts
        @carts.each do |cart|
            @order_product = OrderProduct.new
            @order_product.number = cart.number
            @order_product.subtotal_price = (cart.product.price*1.1).round * cart.number
            @order_product.order_id = @order.id
            @order_product.product_id = cart.product_id
            @order_product.save
        end
        current_user.carts.destroy_all
        pp @order.errors.full_messages
        redirect_to finish_orders_path
    end
# 注文履歴一覧ページ
    def index
        @user = current_user
        @orders = @user.orders.order(created_at: :desc)
    end
# 注文履歴詳細ページ
    def show
        @order = Order.find(params[:id])
        @order_products = @order.order_products
    end
private
    def order_params
        params.require(:order).permit(:payment_method, :postcode, :address, :name, :user_id, :delivery_cost, :total_price, :order_status)
    end
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/admin/orders/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <div class="row">
        <div class="col-xs-1"> </div>
        <div class="col-xs-10">
          <nav>
            <ul class="nav-list">
              <% if admin_signed_in? %>
              <span class="margin-right"><%= link_to "商品一覧", admin_products_path %></span>
              <span class="margin-right"><%= link_to "会員一覧", admin_users_path %></span>
              <span class="margin-right"><%= link_to "注文履歴一覧", admin_orders_path %></span>
              <span class="margin-right"><%= link_to "ジャンル管理", admin_genres_path %></span>
              <% else %>
              <% end %>
            </ul>
          </nav>
        </div>
        <div class="col-xs-1"> </div>
      </div>
      <div class="row">
        <div class="col-xs-1"> </div>
        <div class="col-xs-6">
          <br><br>
<span class="fontsize-cart">注文一覧画面</span>
<br><br>
<table class="table table-bordered">
  <thead>
    <tr>
      <th>購入日時</th>
      <th>購入者</th>
      <th>注文個数</th>
      <th>ステータス</th>
    </tr>
  </thead>
  <tbody>
    <% @orders.each do |order| %>
    <tr>
      <td>
        <%= link_to admin_order_path(order.id) do  %>
        <%= order.created_at.strftime('%Y/%m/%d %H:%M:%S') %>
        <% end %>
      </td>
      <td>
        <%= order.user.last_name + order.user.first_name %>
      </td>
      <% total = 0 %>
      <!-- 注文個数 -->
      <% order.order_products.each do |order_product| %>
      <% total += order_product.number %>
      <% end %>
      <td>
        <%= total %>
      </td>
      <!-- ステータス -->
      <td>
        <%= order.order_status %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>
<%= paginate @orders, class: "paginate" %>


  </div>
        <div class="col-xs-4"> </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/orders/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <div class="row">
        <div class="col-xs-1"> </div>
        <div class="col-xs-10">
          <nav>
            <ul class="nav-list">
              <% if admin_signed_in? %>
              <span class="margin-right"><%= link_to "商品一覧", admin_products_path %></span>
              <span class="margin-right"><%= link_to "会員一覧", admin_users_path %></span>
              <span class="margin-right"><%= link_to "注文履歴一覧", admin_orders_path %></span>
              <span class="margin-right"><%= link_to "ジャンル管理", admin_genres_path %></span>
              <% else %>
              <% end %>
            </ul>
          </nav>
        </div>
        <div class="col-xs-1"> </div>
      </div>
      <div class="row">
        <div class="col-xs-1"> </div>
        <div class="col-xs-6">
          <br><br>
<span class="fontsize-cart">注文詳細画面</span>
<br><br>

<%= form_for(@order, {:url => admin_order_path}) do |f| %>
<table>
  <tr>
    <th>購入者</th>
    <td>
      <%= link_to @user.last_name + @user.first_name, admin_user_path(@user.id) %>
    </td>
  </tr>
  <tr>
    <th>配送先</th>
    <td>
      <% f.hidden_field :postcode, value:@order.postcode %>
      <% f.hidden_field :address, value:@order.address %>
      <% f.hidden_field :name, value:@order.name %>
      <%= @order.postcode %>
      <%= @order.address %>
      <br>
      <%= @order.name %>
    </td>
  </tr>
  <tr>
    <th>支払方法</th>
    <td>
      <% f.hidden_field :payment_method, value:@order.payment_method %>
      <%= @order.payment_method %>
    </td>
  </tr>
  <tr>
    <th>注文ステータス　</th>
    <td>
      <%= f.select :order_status, Order.order_statuses.keys.to_a, {},　class: "form-control"%>
      <!-- <%= @order.order_status %> -->
      <%= f.submit "更新", class: "btn btn-primary" %>
    </td>
  </tr>
</table>
<br><br>
<table class="table table-bordered">
  <tr>
    <th>商品名</th>
    <th>単価（税込み）</th>
    <th>数量</th>
    <th>製作ステータス</th>
  </tr>
  <%= f.fields_for :order_products do |t| %>
  <tr>
    <td>
      <%= t.object.product.product_name %>
    </td>
    <td>
      <%= (t.object.product.price*1.1).round %>
    </td>
    <td>
      <%= t.object.number %>
    </td>
    <td>
      <%= t.select :make_status, OrderProduct.make_statuses.keys.to_a, {} %>
    </td>
  </tr>
  <% end %>
</table>
<table>
  <tr>
    <th>商品合計</th>
    <td>
      <%= @order.total_price - @order.delivery_cost %>
    </td>
  </tr>
  <tr>
    <th>送料</th>
    <td>
      <%= f.hidden_field :delivery_cost, value:800 %>800
    </td>
  </tr>
  <tr>
    <th>請求金額合計　</th>
    <td>
      <% f.hidden_field :total_price, value:@order.total_price %>
      <%= @order.total_price %>
    </td>
  </tr>
</table>
<% end %>


  </div>
        <div class="col-xs-4"> </div>
      </div>
    </div>
  </div>
</div>