config/routes.rb
Rails.application.routes.draw do

  devise_for :admins, :controllers => {
    sessions: 'admins/sessions',
    passwords: 'admins/passwords',
    registrations: 'admins/registrations'
   }
  namespace :admin do
    resources :users, only: [:index, :show, :edit, :update, :destroy]
    resources :products, only: [:new, :create, :index, :show, :edit, :update, :delete]
    resources :genres, only: [:index, :create, :update, :destroy, :edit] do
      member do
        patch 'genre_restore'
      end
    end
    resources :orders, only: [:index, :show, :update]
    get 'top' => 'admins#top'
  end


  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations'
  }
  root 'products#index'
  get '/products/:genre_id/genre', to:'products#index', as: 'genres'
  resources :users, only: [:show]
  resources :products, only: [:index, :show]
  resources :carts, only: [:create, :index, :destroy, :update]
  delete '/carts_delete' => 'carts#carts_delete' ,as: 'carts_delete'

  resources :orders, only: [:new, :create, :index, :show] do
    collection do
      post 'check'
      get 'finish'
    end
  end
  get '/orders_check' => 'orders#check',as: 'orders_check'
  resources :sends, only: [:edit, :index, :delete, :update, :create]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/genre.rb
class Genre < ApplicationRecord
	acts_as_paranoid
	has_many :products
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  before_action :authenticate_admin!

  def index
    @genre = Genre.new
    @genres = Genre.with_deleted
  end
  def create
    @genre = Genre.new(genre_params)
    @genre.save
    redirect_to admin_genres_path
  end
  def edit
    @genre = Genre.find(params[:id])
  end
  def update
    @genre = Genre.find(params[:id])
    @genre.update(genre_params)
    redirect_to admin_genres_path
  end
  def destroy
    	@genre = Genre.find(params[:id])
      @products = @genre.products
      @products.destroy_all
    	@genre.destroy
    	redirect_to admin_genres_path
  end
  def genre_restore
      @genre =  Genre.only_deleted.find(params[:id]).restore
      @products =  Product.only_deleted.where(genre_id: @genre.id)
      @products.each do |product|
        product.restore
      end
      redirect_to admin_genres_path
  end
private
    def genre_params
        params.require(:genre).permit(:genre_name)
    end
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/views/admin/genres/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <div class="row">
        <div class="col-xs-1"> </div>
        <div class="col-xs-10">
          <nav>
            <ul class="nav-list">
              <% if admin_signed_in? %>
              <span class="margin-right"><%= link_to "商品一覧", admin_products_path %></span>
              <span class="margin-right"><%= link_to "会員一覧", admin_users_path %></span>
              <span class="margin-right"><%= link_to "注文履歴一覧", admin_orders_path %></span>
              <span class="margin-right"><%= link_to "ジャンル管理", admin_genres_path %></span>
              <% else %>
              <% end %>
            </ul>
          </nav>
        </div>
        <div class="col-xs-1"> </div>
      </div>
      <div class="row">
        <div class="col-xs-1"> </div>
        <div class="col-xs-10"> <span class="fontsize-cart">ジャンル編集画面</span> <br>
          <%= form_for(@genre, {:url => admin_genre_path}) do |f| %> <br>
            <%= f.text_field :genre_name %>
              <%= f.submit '編集する', :style=> "width:10%;", class: "btn btn-primary" %>
                <% end %>
        </div>
      </div>
      <div class="col-xs-1"> </div>
    </div>
  </div>
</div>

app/views/admin/genres/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <div class="row">
        <div class="col-xs-1"> </div>
        <div class="col-xs-10">
          <nav>
            <ul class="nav-list">
              <% if admin_signed_in? %>
              <span class="margin-right"><%= link_to "商品一覧", admin_products_path %></span>
              <span class="margin-right"><%= link_to "会員一覧", admin_users_path %></span>
              <span class="margin-right"><%= link_to "注文履歴一覧", admin_orders_path %></span>
              <span class="margin-right"><%= link_to "ジャンル管理", admin_genres_path %></span>
              <% else %>
              <% end %>
            </ul>
          </nav>
        </div>
        <div class="col-xs-1"> </div>
      </div>
      <div class="row">
        <div class="col-xs-1"> </div>
        <div class="col-xs-6"> <span class="fontsize-cart">ジャンル管理画面
</span> <br> <br> <br> ジャンル
          <%= form_for(@genre, {:url => admin_genres_path}) do |f| %>
            <%= f.text_field :genre_name, :style=> "width:30%;" %>
              <%= f.submit '追加', class: "btn btn-primary" %>
                <% end %> <br>
                  <p>ジャンル一覧</p>
                  <table class="table table-striped">
                    <thead>
                      <tr>
                        <td colspan="3">ジャンル</td>
                      </tr>
                    </thead>
                    <tbody>
                      <% @genres.each do |genre| %>
                        <tr>
                          <td>
                            <%= genre.genre_name %>
                          </td>
                          <% unless genre.deleted_at? %>
                            <td>
                              <%= link_to "無効にする", admin_genre_path(genre), data: { confirm: "無効にしますか?" }, method: :delete, class: "btn btn-danger" %>
                            </td>
                            <td>
                              <%= link_to "編集する", edit_admin_genre_path(genre), class: "btn btn-primary" %>
                            </td>
                            <% else %>
                              <td>
                                <%= link_to "有効にする", genre_restore_admin_genre_path(genre), method: :patch, class: "btn btn-primary" %>
                              </td>
                              <td>
                                <%= link_to "編集する", edit_admin_genre_path(genre), class: "btn btn-primary" %>
                              </td>
                              <% end %>
                        </tr>
                        <% end %>
                    </tbody>
                  </table>
        </div>
        <div class="col-xs-4"> </div>
      </div>
    </div>
  </div>
</div>