config/routes.rb
Rails.application.routes.draw do

  devise_for :admins, :controllers => {
    sessions: 'admins/sessions',
    passwords: 'admins/passwords',
    registrations: 'admins/registrations'
   }
  namespace :admin do
    resources :users, only: [:index, :show, :edit, :update, :destroy]
    resources :products, only: [:new, :create, :index, :show, :edit, :update, :delete]
    resources :genres, only: [:index, :create, :update, :destroy, :edit] do
      member do
        patch 'genre_restore'
      end
    end
    resources :orders, only: [:index, :show, :update]
    get 'top' => 'admins#top'
  end


  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations'
  }
  root 'products#index'
  get '/products/:genre_id/genre', to:'products#index', as: 'genres'
  resources :users, only: [:show]
  resources :products, only: [:index, :show]
  resources :carts, only: [:create, :index, :destroy, :update]
  delete '/carts_delete' => 'carts#carts_delete' ,as: 'carts_delete'

  resources :orders, only: [:new, :create, :index, :show] do
    collection do
      post 'check'
      get 'finish'
    end
  end
  get '/orders_check' => 'orders#check',as: 'orders_check'
  resources :sends, only: [:edit, :index, :delete, :update, :create]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
	belongs_to :genre
	has_many :carts
	has_many :order_products
	attachment :product_image
	enum sale_status: {販売中: 1, 販売停止: 2}
	acts_as_paranoid
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
	before_action :authenticate_admin!

	def new
	   @product = Product.new
	end

	def create
	   @product = Product.new(product_params)
  	   @product.save
  	   redirect_to admin_products_path
	end

	def show
        @product = Product.find(params[:id])
	end

	def index
		@products = Product.all
	end

	def edit
        @product = Product.find(params[:id])
	end

    def update
        @product = Product.find(params[:id])
        @product.update(product_params)
        redirect_to admin_product_path(@product)
    end

private
    def product_params
        params.require(:product).permit(:product_name, :price, :product_image, :product_intoroduction, :genre_id, :sale_status)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

	def show
	 @product = Product.find(params[:id])
	 @cart = Cart.new
     @genres = Genre.all
    end

    def index
    if params[:genre_id]
     @products = Product.where(genre_id: params[:genre_id])
    else
     @products = Product.all
     end

     @genres = Genre.all
    end

end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admin/products/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <div class="row">
        <div class="col-xs-1"> </div>
        <div class="col-xs-10">
          <nav>
            <ul class="nav-list">
              <% if admin_signed_in? %>
              <span class="margin-right"><%= link_to "商品一覧", admin_products_path %></span>
              <span class="margin-right"><%= link_to "会員一覧", admin_users_path %></span>
              <span class="margin-right"><%= link_to "注文履歴一覧", admin_orders_path %></span>
              <span class="margin-right"><%= link_to "ジャンル管理", admin_genres_path %></span>
              <% else %>
              <% end %>
            </ul>
          </nav>
        </div>
        <div class="col-xs-1"> </div>
      </div>
      <div class="row">
        <div class="col-xs-1"> </div>
        <div class="col-xs-5"> <span class="fontsize-cart">商品編集画面
</span> <br><br>
          <%= form_for(@product, {:url => admin_product_path}) do |f| %>
            <p>商品画像</p>
            <%= attachment_image_tag @product, :product_image, format: 'jpeg', fallback: "no_image.jpg", size: "400x250" %> <br><br>
              <%= f.attachment_field :product_image %>
        </div>
        <div class="col-xs-6"> <br><br><br>
          <p>商品名</p>
          <%= f.text_field :product_name, autofocus: true, class:"form-control", id:"inputproductname" %> <br>
            <p>商品説明文</p>
            <%= f.text_area :product_intoroduction, autofocus: true, class:"form-control", id:"inputproductintoroduction" %> <br>
              <p>税抜き価格</p>
              <%= f.text_field :price, autofocus: true, class:"form-control", id:"inputprice" %> <br>
                <p>ジャンル選択</p>
                <%= f.collection_select :genre_id, Genre.all, :id, :genre_name %> <br><br>
                  <p>ステータス選択</p>
                  <%= f.select :sale_status, Product.sale_statuses.keys.to_a, {} %> <br><br>
                    <%= f.submit "変更を保存", class: "btn btn-primary", :style=> "width:40%;" %>
                      <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/products/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <div class="row">
        <div class="col-xs-1"> </div>
        <div class="col-xs-10">
          <nav>
            <ul class="nav-list">
              <% if admin_signed_in? %>
              <span class="margin-right"><%= link_to "商品一覧", admin_products_path %></span>
              <span class="margin-right"><%= link_to "会員一覧", admin_users_path %></span>
              <span class="margin-right"><%= link_to "注文履歴一覧", admin_orders_path %></span>
              <span class="margin-right"><%= link_to "ジャンル管理", admin_genres_path %></span>
              <% else %>
              <% end %>
            </ul>
          </nav>
        </div>
        <div class="col-xs-1"> </div>
      </div>
      <div class="row">
        <div class="col-xs-1"> </div>
        <div class="col-xs-10"> <span class="fontsize-cart">商品一覧画面</span>
          <div style="text-align : right">
            <%= link_to "商品の追加", new_admin_product_path, class: "btn btn-primary" %>
          </div> <br><br>
          <table class="table table-striped">
            <thead>
              <tr>
                <td>商品ID </td>
                <td>商品名 </td>
                <td>税抜き価格 </td>
                <td>ジャンル </td>
                <td>ステータス </td>
              </tr>
            </thead>
            <tbody>
              <tr>
                <% @products.each do |product| %>
                  <td>
                    <%= product.id %>
                  </td>
                  <td>
                    <%= link_to admin_product_path(product) do %>
                    <%= product.product_name %>
                    <% end %>
                  </td>
                  <td>
                    <%= product.price %>
                  </td>
                  <td>
                    <%= product.genre.genre_name %>
                  </td>
                  <td>
                    <%= product.sale_status %>
                  </td>
              </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
      <div class="col-xs-1"> </div>
    </div>
  </div>
</div>

app/views/admin/products/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <div class="row">
        <div class="col-xs-1"> </div>
        <div class="col-xs-10">
          <nav>
            <ul class="nav-list">
              <% if admin_signed_in? %>
              <span class="margin-right"><%= link_to "商品一覧", admin_products_path %></span>
              <span class="margin-right"><%= link_to "会員一覧", admin_users_path %></span>
              <span class="margin-right"><%= link_to "注文履歴一覧", admin_orders_path %></span>
              <span class="margin-right"><%= link_to "ジャンル管理", admin_genres_path %></span>
              <% else %>
              <% end %>
            </ul>
          </nav>
        </div>
        <div class="col-xs-1"> </div>
      </div>
      <div class="row">
        <div class="col-xs-1"> </div>
        <div class="col-xs-6"> <span class="fontsize-cart">商品新規登録画面
</span> <br> <br> <br>
          <%= form_for(@product, {:url => admin_products_path}) do |f| %>
            <p>商品画像 </p>
            <%= f.attachment_field :product_image %> <br>
              <p>商品名 </p>
              <%= f.text_field :product_name, autofocus: true, class:"form-control", id:"inputproductname" %> <br>
                <p>商品説明文 </p>
                <%= f.text_area :product_intoroduction, autofocus: true, class:"form-control", id:"inputproductintoroduction" %> <br>
                  <p>税抜き価格 </p>
                  <%= f.text_field :price, autofocus: true, class:"form-control", id:"inputprice" %> <br>
                    <p>ジャンル選択 </p>
                    <%= f.collection_select :genre_id, Genre.all, :id, :genre_name %> <br> <br>
                      <p>販売ステータス </p>
                      <%= f.select :sale_status, Product.sale_statuses.keys.to_a, {} %> <br> <br>
                        <%= f.submit "新規登録", class: "btn btn-primary", :style=> "width:40%;" %>
                          <% end %>
        </div>
        <div class="col-xs-4"> </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/products/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <div class="row">
        <div class="col-xs-1"> </div>
        <div class="col-xs-10">
          <nav>
            <ul class="nav-list">
              <% if admin_signed_in? %>
              <span class="margin-right"><%= link_to "商品一覧", admin_products_path %></span>
              <span class="margin-right"><%= link_to "会員一覧", admin_users_path %></span>
              <span class="margin-right"><%= link_to "注文履歴一覧", admin_orders_path %></span>
              <span class="margin-right"><%= link_to "ジャンル管理", admin_genres_path %></span>
              <% else %>
              <% end %>
            </ul>
          </nav>
        </div>
        <div class="col-xs-1"> </div>
      </div>
      <div class="row">
        <div class="col-xs-1"> </div>
        <div class="col-xs-5"> <span class="fontsize-cart">商品詳細画面</span> <br> <br>
          <p>商品画像 </p>
          <%= attachment_image_tag @product, :product_image, format: 'jpeg', fallback: "no_image.jpg", size: "400x250" %> <br> <br> </div>
        <div class="col-xs-6"> <br> <br> <br>
          <p>商品名 </p>
          <p class="fontsize">
            <%= @product.product_name %>
          </p> <br>
          <p>商品説明文 </p>
          <p>
            <%= @product.product_intoroduction %>
          </p> <br>
          <p>税抜き価格 </p>
          <p>
            <%= @product.price %>円 </p> <br>
          <p>ジャンル </p>
          <p>
            <%= @product.genre.genre_name %>
          </p> <br> <br>
          <p>販売ステータス </p>
          <%= @product.sale_status %>
          <br><br>
          <%= link_to "編集する", edit_admin_product_path(@product), data: {"turbolinks" => false} , class: "btn btn-primary" %>
        </div>
      </div>
    </div>
  </div>
</div>